### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-accepts-serializer#18]
As titled, this module would benefit for 100% code coverage

**Comment by psyycker** [comment]
Hi, I'm working on this task currently and it doesn't seems that `if (cacheValue) return cacheValue` (SerializerManager.js line 22) is ever true.
Any idea how I could make this happen?

**Comment by mcollina** [comment]
I think you would be ok in calling the same route twice on the same instance. Have you tried that?

**Comment by psyycker** [comment]
Yes, I gave it a go and it looks like it's still not covering the line
```
t.test('application/yaml -> yaml', t => {
    t.plan(6)
    fastify.inject({
      method: 'GET',
      url: '/request',
      payload: {},
      headers: {
        accept: 'application/yaml'
      }
    }, (err, res) => {
      t.error(err)
      t.strictDeepEqual(res.headers['content-type'], 'application/yaml')
      t.strictDeepEqual(res.payload, YAML.stringify({ pippo: 'pluto' }))
    })

    fastify.inject({
      method: 'GET',
      url: '/request',
      payload: {},
      headers: {
        accept: 'application/yaml'
      }
    }, (err, res) => {
      t.error(err)
      t.strictDeepEqual(res.headers['content-type'], 'application/yaml')
      t.strictDeepEqual(res.payload, YAML.stringify({ pippo: 'pluto' }))
    })
  })
```
I'm for not trying to make it trigger, I'll write proper test when I'll finally be able to

**Comment by mcollina** [comment]
They might need to be nested

**Comment by climba03003** [comment]
If I am not wrong, the cache in this plugin will never be fired. 

The main reason is that [```SerializerManager.expand```](https://github.com/fastify/fastify-accepts-serializer/blob/master/SerializerManager.js#L54-L56) always initialize a new instance and for the [```preHandler```](https://github.com/fastify/fastify-accepts-serializer/blob/master/index.js#L24) hook which call the ```SerializerManager.expand``` will lead to always having new cache for each route. 

As a result, calling same route multiple times or nesting will not trigger the cache.

**Comment by Eomm** [comment]
> As a result, calling same route multiple times or nesting will not trigger the cache.

This seems a bug to me!
