### ISSUE TITLE
Cache is not triggered

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-accepts-serializer#30]
Reading the old code:
https://github.com/fastify/fastify-accepts-serializer/tree/v3.0.1

the cache behaviour can works if the users doesn't customize the `serializer` in the route options.

So the cache can be enabled and used from the `globalSerializerManager` when `reply.serializer` is empty

--

If I am not wrong, the cache in this plugin will never be fired. 

The main reason is that [```SerializerManager.expand```](https://github.com/fastify/fastify-accepts-serializer/blob/master/SerializerManager.js#L54-L56) always initialize a new instance and for the [```preHandler```](https://github.com/fastify/fastify-accepts-serializer/blob/master/index.js#L24) hook which call the ```SerializerManager.expand``` will lead to always having new cache for each route. 

As a result, calling same route multiple times or nesting will not trigger the cache.

_Originally posted by @climba03003 in https://github.com/fastify/fastify-accepts-serializer/issues/18#issuecomment-729910713_

**Comment by climba03003** [comment]
The ```globalSerializerManager``` only triggered ```findSerializer``` once when ```fastify``` initial. It is the only function that will trigger the cache. So, even if you do not specify ```reply.serializer```. The cache can not trigger either.

I have tried to fix this issue before when I first scan the code by inheriting the cache. But no luck.
